первая версия второго спринта
chesKaterina/middle.messenger.praktikum.yandex pull request #3
Opened 2022-09-11 10:33 UTC by chesKaterina

Добрый день. Проект собирается, но в браузере белый экран. Не могу понять в чем дело, может что-то не учла. Просьба помочь разобраться в чем дело с отображением.

2022-09-11 13:19 UTC, agadoev commented
Привет, Кристина!
Я запустил проект и все страницы открываются. Можешь уточинть, что конкретно у тебя не работает?

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37894659/189529759-c5a4c233-897e-456d-927d-87be5eb35c52.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37894659/189529763-f390d5f6-04ed-4438-9ff2-269c89c02169.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37894659/189529772-af12da64-6d0d-40f0-adba-f3395ec65902.png">

2022-09-11 14:09 UTC, chesKaterina commented
Привет! 
собираю проект npm run build далее запускаю npm run start, на 3000 порту в браузере показывает пустую страницу 


![Снимок](https://user-images.githubusercontent.com/111084605/189531962-5089458a-a630-4a4f-a7f3-5da0f8d59930.PNG)

2022-09-11 14:18 UTC, agadoev commented
Так сложно сказать, но дело скорее всего не в коде, потому что у меня с первого раза все запустилось.
Попробуй пока следующие варианты:
1. Почистить кеш в хроме
2. Позапускать в других браузерах
3. Запусти через npm run dev и перейди на localhost:1234

2022-09-11 14:25 UTC, chesKaterina commented
Тоже самое (((

2022-09-11 14:45 UTC, agadoev commented
пропиши npm run start, перейди на localhost:3000 и заскринь что выводится на консоли

2022-09-11 14:56 UTC, chesKaterina commented
Я попробовала запустить проект из ветки main и у меня выходят такие же страницы как у вас на скрине. Может у вас запустился проект из ветки main, а не из ветки sprint_2?

А так вот что получилось в консоли браузера и VS code
![console br](https://user-images.githubusercontent.com/111084605/189534377-123efeba-80fb-4953-8c5c-d83eb94cf9c7.PNG)
![console](https://user-images.githubusercontent.com/111084605/189534378-f6c25072-9e7e-4eab-acdd-c670809ac21d.PNG)

2022-09-12 06:01 UTC, agadoev commented on src/utils/HttpTransport.ts
> +enum METHODS {
Этот функционал вроде как относится к следующему спринту. Хорошим тоном считается когда в MR лежат только те изменения, которые относятся к задаче, и никакие более. Это упростит задачу и тебе, и ревьюеру

2022-09-12 06:02 UTC, agadoev commented on tsconfig.json
> +    // "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
Давай это раскомментируем. Эта настройка принуждает нас всегда указывать возвращаемый тип, и это очень сильно помогает потом при работе с кодом

2022-09-12 06:03 UTC, agadoev commented
Я воспроизвел у себя и в итоге у меня отрендерилось
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/37894659/189584015-be4e76f9-e7a3-453d-9797-a38ef3de0203.png">
почему чат пустой - разберешься уже сама. Там проблема была в методе _render, я в комментах отписал подробнее

2022-09-13 16:41 UTC, chesKaterina commented
Добрый день!
Я так и не смогла разобраться с проблемами отображением страницы, поэтому решила откатиться к версии первого спринта и реализовала с использованием hbs.
Также валидатор не выводит сообщения (уже и не знаю почему), при попытке войти в систему при незаполненных полях, он не пускает.

2022-09-13 21:16 UTC, agadoev requested changes
Скорее всего он не выводит ошибку, потому что не находит форму по указанному селектору.
<img width="660" alt="image" src="https://user-images.githubusercontent.com/37894659/190009599-b3dedaf1-6503-4be2-9448-fc4d4f6446aa.png">

Я заметил, что не все исправлено из первой итерации ревью. Все таки надо эти замечания поправить + я посмотрел реализацию валидатора и есть несколько предложений как улучшить код.
Порекомендую пару книг, которые помогут тебе улучшить понимание кода - "Чистый код" и "Чистая архитектура" Роберта Мартина. Так же если чувствуешь, что тебе сложно или есть вопросы, можешь писать мне в tg (в профиле указан), попробуем разобраться. Пока что возвращаю работу, но верю, что ты справишься : thumbsup:

2022-09-13 21:16 UTC, agadoev commented on src/utils/validator.ts
> +export function isErrorMes(name: string, error: string) {
Если функция начинается с is, я ожидаю, что она вернет boolean. Сейчас функция просто проставляет ошибку. Я предлагаю изменить название на setError, это название будет точнее отражать суть функции

2022-09-13 21:16 UTC, agadoev commented on src/utils/validator.ts
> +export function isDelError(name: string) {
Давай переименуем в removeError

2022-09-13 21:16 UTC, agadoev commented on src/utils/validator.ts
> +  const form = document.querySelector("." + selectorForm) as HTMLDivElement;
1. Почему HTMLDivElement, если по идее должен быть HTMLFormElement?
2. Лучше не использовать явное приведенеи типов, потому что это костыль. Тут можно записать вот так
```suggestion
  const form = document.querySelector<HTMLDivElement>("." + selectorForm);
```
3. В селекторе уже должна быть точка, тут конкатенировать строки не нужно

2022-09-13 21:16 UTC, agadoev commented on src/utils/validator.ts
> +  let error = 0;
Если это счетчик, давай в названии переменной обозначим, что это счетчик
```suggestion
  let errorsCounter = 0;
```

2022-09-13 21:16 UTC, agadoev commented on src/utils/validator.ts
> +      console.log(arrForm);
Отладочные console.log'и мы убираем

2022-09-14 17:59 UTC, agadoev approved these changes
Привет еще раз :)
Спасибо за правки. Не увидел изменений в файле sign_in.ts. Они небольшие, поправить их перед мержем, пожалуйста. Все ок, работа принимается. Удачи в следующем спринте :)

2022-09-14 17:59 UTC, agadoev commented on tsconfig.json
> +    "noImplicitReturns": true,                        /* Enable error reporting for codepaths that do not explicitly return in a function. */
наверное я не очень понятно выложил свою мысль по поводу этих правил. Я имел в виду только правило ```noImplicitReturns: true```, а не все

2022-09-14 19:30 UTC, merged